/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.demo.bean.jpa.AdresseEntity;
import org.demo.persistence.commons.fake.GenericFakeService;
import org.demo.persistence.services.AdressePersistence;

/**
 * Fake persistence service implementation ( entity "Adresse" )
 *
 * @author Telosys Tools Generator
 */
public class AdressePersistenceFAKE extends GenericFakeService<AdresseEntity> implements AdressePersistence {

	public AdressePersistenceFAKE () {
		super(AdresseEntity.class);
	}
	
	protected AdresseEntity buildEntity(int index) {
		AdresseEntity entity = new AdresseEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setRue( nextString() ) ;
		entity.setCp( nextInteger() ) ;
		entity.setVille( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(AdresseEntity entity) {
		log("delete ( AdresseEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(AdresseEntity entity) {
		log("insert ( AdresseEntity : " + entity + ")" ) ;
	}

	public AdresseEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<AdresseEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<AdresseEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<AdresseEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public AdresseEntity save(AdresseEntity entity) {
		log("insert ( AdresseEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<AdresseEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
