/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.demo.bean.jpa.PaysEntity;
import org.demo.persistence.commons.fake.GenericFakeService;
import org.demo.persistence.services.PaysPersistence;

/**
 * Fake persistence service implementation ( entity "Pays" )
 *
 * @author Telosys Tools Generator
 */
public class PaysPersistenceFAKE extends GenericFakeService<PaysEntity> implements PaysPersistence {

	public PaysPersistenceFAKE () {
		super(PaysEntity.class);
	}
	
	protected PaysEntity buildEntity(int index) {
		PaysEntity entity = new PaysEntity();
		// Init fields with mock values
		entity.setCode( nextString() ) ;
		entity.setName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(PaysEntity entity) {
		log("delete ( PaysEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( String code ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(PaysEntity entity) {
		log("insert ( PaysEntity : " + entity + ")" ) ;
	}

	public PaysEntity load( String code ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<PaysEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<PaysEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<PaysEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public PaysEntity save(PaysEntity entity) {
		log("insert ( PaysEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<PaysEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
