/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.AdherentEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.AdherentPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Adherent" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AdherentPersistenceJPA extends GenericJpaService<AdherentEntity, String> implements AdherentPersistence {

	/**
	 * Constructor
	 */
	public AdherentPersistenceJPA() {
		super(AdherentEntity.class);
	}

	@Override
	public AdherentEntity load( String login ) {
		return super.load( login );
	}

	@Override
	public boolean delete( String login ) {
		return super.delete( login );
	}

	@Override
	public boolean delete(AdherentEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getLogin() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("AdherentEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
