/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.PaysEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.PaysPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Pays" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PaysPersistenceJPA extends GenericJpaService<PaysEntity, String> implements PaysPersistence {

	/**
	 * Constructor
	 */
	public PaysPersistenceJPA() {
		super(PaysEntity.class);
	}

	@Override
	public PaysEntity load( String code ) {
		return super.load( code );
	}

	@Override
	public boolean delete( String code ) {
		return super.delete( code );
	}

	@Override
	public boolean delete(PaysEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getCode() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PaysEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
