/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package db.services.interfaces;

import java.util.List;
import java.util.Map;

import db.dao.PaysDAO;

/**
 * Basic persistence operations for entity "PaysBean"
 * 
 * This database.bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface PaysPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pays
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PaysDAO pays) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param code
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String code) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pays
	 */
	public void insert(PaysDAO pays) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param code
	 * @return the entity loaded (or null if not found)
	 */
	public PaysDAO load(String code) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PaysDAO> loadAll() ;



	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pays
	 * @return
	 */
	public PaysDAO save(PaysDAO pays) ;



	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
