/*
 * Created on 1 nov. 2017 ( Time 17:24:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ADHERENT"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ADHERENT", schema="APP" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AdherentEntity.countAll", query="SELECT COUNT(x) FROM AdherentEntity x" )
} )
public class AdherentEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="LOGIN", nullable=false, length=30)
    private String     login        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="MDP", nullable=false, length=30)
    private String     mdp          ;

    @Column(name="NOM", nullable=false, length=30)
    private String     nom          ;

    @Column(name="PRENOM", nullable=false, length=30)
    private String     prenom       ;

	// "adresse" (column "ADRESSE") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ADRESSE", referencedColumnName="ID")
    private AdresseEntity adresse2    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AdherentEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLogin( String login ) {
        this.login = login ;
    }
    public String getLogin() {
        return this.login;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : MDP ( VARCHAR ) 
    public void setMdp( String mdp ) {
        this.mdp = mdp;
    }
    public String getMdp() {
        return this.mdp;
    }

    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRENOM ( VARCHAR ) 
    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }
    public String getPrenom() {
        return this.prenom;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAdresse2( AdresseEntity adresse2 ) {
        this.adresse2 = adresse2;
    }
    public AdresseEntity getAdresse2() {
        return this.adresse2;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(login);
        sb.append("]:"); 
        sb.append(mdp);
        sb.append("|");
        sb.append(nom);
        sb.append("|");
        sb.append(prenom);
        return sb.toString(); 
    } 

}
