/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.sql.Blob;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ARTICLE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ARTICLE", schema="APP" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ArticleEntity.countAll", query="SELECT COUNT(x) FROM ArticleEntity x" )
} )
public class ArticleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="CODE", nullable=false, length=3)
    private String     code         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", nullable=false, length=30)
    private String     nom          ;

    @Column(name="PRIX", nullable=false)
    private Double     prix         ;

    @Column(name="STOCK", nullable=false)
    private Integer    stock        ;

    @Lob
    @Column(name="IMAGE")
    private Blob       image        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ArticleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCode( String code ) {
        this.code = code ;
    }
    public String getCode() {
        return this.code;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRIX ( DOUBLE ) 
    public void setPrix( Double prix ) {
        this.prix = prix;
    }
    public Double getPrix() {
        return this.prix;
    }

    //--- DATABASE MAPPING : STOCK ( INTEGER ) 
    public void setStock( Integer stock ) {
        this.stock = stock;
    }
    public Integer getStock() {
        return this.stock;
    }

    //--- DATABASE MAPPING : IMAGE ( BLOB ) 
    public void setImage( Blob image ) {
        this.image = image;
    }
    public Blob getImage() {
        return this.image;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(code);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(prix);
        sb.append("|");
        sb.append(stock);
        // attribute 'image' not usable (type = Blob)
        return sb.toString(); 
    } 

}
