INSERT INTO PAYS VALUES 
    ('FR','FRANCE'),('AT','AUTRICHE'),('AR','ARGENTINE'),('BL','BELGIQUE'),('CH','SUISSE'),('ES','ESPAGNE'),('FI','FINLANDE'),('GB','GRANDE BRETAGNE'),('IT','ITALIE'),('NL','PAYS-BAS'),('NO','NORVEGE'),('PT','PORTUGAL'),('SE','SUEDE'),('US','ETATS UNIS');
	
INSERT INTO ADRESSE VALUES
	(1,'RUE DU SAPIN',44300,'Nantes','FR');
	
INSERT INTO ADHERENT VALUES 
	('DEDE1','mdpdelamort','Jean','Dédé',1);
	
INSERT INTO ARTICLE VALUES
	('PU1','PULL EMN 1',25.50,56,NULL);