CREATE TABLE PAYS
    (CODE VARCHAR(2) PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL);
	
CREATE TABLE ADHERENT
	(LOGIN VARCHAR(30) PRIMARY KEY,
	MDP VARCHAR(30) NOT NULL,
	NOM VARCHAR(30) NOT NULL,
	PRENOM VARCHAR(30) NOT NULL,
	ADRESSE INT REFERENCES ADRESSE(ID));
	
CREATE TABLE ADRESSE
	(ID INT PRIMARY KEY,
	RUE VARCHAR(50),
	CP INT,
	VILLE VARCHAR(30),
	PAYS VARCHAR(2) REFERENCES PAYS(CODE));
	
CREATE TABLE ARTICLE
	(CODE VARCHAR(3) PRIMARY KEY,
	NOM VARCHAR(30) NOT NULL,
 	DESCRIPTION VARCHAR(60) NOT NULL,
	PRIX DOUBLE NOT NULL,
	STOCK INT NOT NULL,
	IMAGE VARCHAR(60) );
