/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.AdherentEntity;
import org.demo.mock.AdherentEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.AdherentPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Adherent persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class AdherentPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		AdherentPersistence service = PersistenceServiceProvider.getService(AdherentPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Adherent persistence : delete + load ..." );
		
		AdherentPersistence service = PersistenceServiceProvider.getService(AdherentPersistence.class);
		
		AdherentEntityMock mock = new AdherentEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(AdherentPersistence service, AdherentEntityMock mock, String login ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		AdherentEntity entity = service.load( login );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( login ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Adresse
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( login );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
