/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.PaysEntity;
import org.demo.mock.PaysEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.PaysPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Pays persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class PaysPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		PaysPersistence service = PersistenceServiceProvider.getService(PaysPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Pays persistence : delete + load ..." );
		
		PaysPersistence service = PersistenceServiceProvider.getService(PaysPersistence.class);
		
		PaysEntityMock mock = new PaysEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(PaysPersistence service, PaysEntityMock mock, String code ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		PaysEntity entity = service.load( code );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( code ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( code );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
