
/*
 * Created on 1 nov. 2017 ( Time 17:24:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.AdherentEntity;
import org.demo.mock.tool.MockValues;

public class AdherentEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AdherentEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(30) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AdherentEntity createInstance( String login ) {
		AdherentEntity entity = new AdherentEntity();
		// Init Primary Key fields
		entity.setLogin( login) ;
		// Init Data fields
		entity.setMdp( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setNom( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setPrenom( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setAdresse2( TODO ) ; // Adresse 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AdherentEntity> createList(int count) {
		List<AdherentEntity> list = new LinkedList<AdherentEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
