
/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.AdresseEntity;
import org.demo.mock.tool.MockValues;

public class AdresseEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AdresseEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AdresseEntity createInstance( Integer id ) {
		AdresseEntity entity = new AdresseEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setRue( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setCp( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setVille( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setPays2( TODO ) ; // Pays 
		// setListOfAdherent( TODO ) ; // List<Adherent> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AdresseEntity> createList(int count) {
		List<AdresseEntity> list = new LinkedList<AdresseEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
