
/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.PaysEntity;
import org.demo.mock.tool.MockValues;

public class PaysEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PaysEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(2) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PaysEntity createInstance( String code ) {
		PaysEntity entity = new PaysEntity();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setName( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAdresse( TODO ) ; // List<Adresse> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PaysEntity> createList(int count) {
		List<PaysEntity> list = new LinkedList<PaysEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
