/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package database.services.interfaces;

import java.util.List;
import java.util.Map;


import database.dao.AdresseDAO;

/**
 * Basic persistence operations for entity "Adresse"
 * 
 * This database.bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface AdressePersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adresse
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(AdresseDAO adresse) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param id
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer id) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adresse
	 */
	public void insert(AdresseDAO adresse) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param id
	 * @return the entity loaded (or null if not found)
	 */
	public AdresseDAO load(Integer id) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<AdresseDAO> loadAll() ;



	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param adresse
	 * @return
	 */
	public AdresseDAO save(AdresseDAO adresse) ;


	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
