/*
 * Created on 1 nov. 2017 ( Date ISO 2017-11-01 - Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package db.services.jpa;

import java.util.HashMap;
import java.util.Map;

public class JPAEnvironments {

	private final static JPAEnvironments singleInstance = new JPAEnvironments();
	
	private final Map<String,JPAEnvironment> environments ;

	private JPAEnvironments() {
		super();
		this.environments = new HashMap<String,JPAEnvironment>();
	}
	
	public final static JPAEnvironments getInstance() {
		return singleInstance ;
	}
	
	public JPAEnvironment getJpaEnvironment(final String peristanceUnitName ) {
		JPAEnvironment env = environments.get(peristanceUnitName) ;
		if ( env == null ) {
			env = createNewJpaEnvironment( peristanceUnitName );
		}
		return env ;
	}

	private synchronized JPAEnvironment createNewJpaEnvironment(final String peristanceUnitName ) {
		JPAEnvironment env = environments.get(peristanceUnitName) ; // double check
		if ( env == null ) {
			env = new JPAEnvironment(peristanceUnitName);
			environments.put(peristanceUnitName, env);
		}
		return env ;
	}
}
