/*
 * Created on 1 nov. 2017 ( Date ISO 2017-11-01 - Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package db.services.jpa;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;

/**
 * Interface d'opération JPA
 *
 * @author Inspired by Telosys Tools for JPA testing
 * @author Juliette FRETAY, Kendall FOREST, Chloé GUILBAUD
 *
 */
public interface JPAOperation {

	/**
	 * Exécute une opération JPA à partir du {@link EntityManager} fourni
	 * @param em l'{@link EntityManager}
	 * @return le résultat de la requête à la base de données
	 * @throws PersistenceException erreur de base de données
	 */
	Object exectue(EntityManager em) throws PersistenceException;
	
}
