/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package db.services.persistence;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import db.dao.AdherentDAO;
import db.services.jpa.JPAService;
import db.services.jpa.JPAOperation;
import db.services.jpa.JPAResult;
import errors.ErrorManagerUtils;

import java.util.Optional;

import static errors.ErrorManagerUtils.manageJPAError;

/**
 * JPA implementation for basic persistence operations ( entity "AdherentBean" )
 *
 * @author Inspired by Telosys Tools for JPA testing
 * @author Juliette FRETAY, Kendall FOREST, Chloé GUILBAUD
 */
public class AdherentJPAPersistence extends JPAService<AdherentDAO, String> implements JPAPersistence<AdherentDAO, String> {

    /**
     * Constructor
     */
    public AdherentJPAPersistence() {
        super(AdherentDAO.class);
    }

    @Override
    public JPAResult<AdherentDAO> load(String login) {
        return super.load(login);
    }

    @Override
    public JPAResult<Boolean> delete(String login) {
        return super.delete(login);
    }

    @Override
    public JPAResult<Boolean> delete(AdherentDAO entity) {
        if (entity != null) {
            return super.delete(entity.getLogin());
        }
        return new JPAResult<>(Optional.of(false));
    }

    @Override
    public JPAResult<Long> countAll() {
        return super.countAll("AdherentDAO.countAll", "countAll AdherentJPA");
    }


}
