/*
 * Created on 1 nov. 2017 ( Time 17:24:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package db.services.persistence;


import db.dao.AdresseDAO;
import db.services.jpa.JPAService;
import db.services.jpa.JPAResult;

import java.util.Optional;

/**
 * JPA implementation for basic persistence operations ( entity "AdresseBean" )
 *
 * @author Inspired by Telosys Tools for JPA testing
 * @author Juliette FRETAY, Kendall FOREST, Chloé GUILBAUD
 *
 */
public class AdresseJPAPersistence extends JPAService<AdresseDAO, Integer> implements JPAPersistence<AdresseDAO, Integer> {

	/**
	 * Constructor
	 */
	public AdresseJPAPersistence() {
		super(AdresseDAO.class);
	}

	@Override
	public JPAResult<AdresseDAO> load(Integer id ) {
		return super.load( id );
	}

	@Override
	public JPAResult<Boolean> delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public JPAResult<Boolean> delete(AdresseDAO entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
        return new JPAResult<>(Optional.of(false));
	}

	@Override
	public JPAResult<Long> countAll() {
        return super.countAll("AdresseDAO.countAll", "countAll() AdresseJPA");
	}

}
