/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package db.services.persistence;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import db.dao.PaysDAO;
import db.services.jpa.JPAService;
import db.services.jpa.JPAOperation;
import db.services.results.JPAResult;

import java.util.Optional;

/**
 * JPA implementation for basic persistence operations ( entity "PaysBean" )
 *
 * @author Telosys Tools Generator
 */
public class PaysJPAPersistence extends JPAService<PaysDAO, String> implements JPAPersistence<PaysDAO, String> {

    /**
     * Constructor
     */
    public PaysJPAPersistence() {
        super(PaysDAO.class);
    }

    @Override
    public JPAResult<PaysDAO> load(String code) {
        return super.load(code);
    }

    @Override
    public JPAResult<Boolean> delete(String code) {
        return super.delete(code);
    }

    @Override
    public JPAResult<Boolean> delete(PaysDAO entity) {
        if (entity != null) {
            return super.delete(entity.getCode());
        }
        return new JPAResult<>(Optional.of(false));
    }

    @Override
    public JPAResult<Long> countAll() {
        // JPA operation definition
        JPAOperation operation = new JPAOperation() {
            @Override
            public Object exectue(EntityManager em) throws PersistenceException {
                Query query = em.createNamedQuery("PaysDAO.countAll");
                return query.getSingleResult();
            }
        };

        JPAResult jpaResult = new JPAResult();
        try {
            Long res = (Long) execute(operation);
            jpaResult.setResult(Optional.of(res));
        } catch (PersistenceException e) {
            JPAService.saveError(jpaResult, e, "countAll() Pays");
        }

        // JPA operation execution
        return jpaResult;
    }

}
