/*
 * Created on 1 nov. 2017 ( Time 17:25:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package db.services.persistence;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import db.dao.PaysDAO;
import db.services.jpa.JPAService;
import db.services.jpa.JPAOperation;
import db.services.jpa.JPAResult;

import java.util.Optional;

import static errors.ErrorManagerUtils.manageJPAError;

/**
 * JPA implementation for basic persistence operations ( entity "PaysBean" )
 *
 * @author Telosys Tools Generator
 */
public class PaysJPAPersistence extends JPAService<PaysDAO, String> implements JPAPersistence<PaysDAO, String> {

    /**
     * Constructor
     */
    public PaysJPAPersistence() {
        super(PaysDAO.class);
    }

    @Override
    public JPAResult<PaysDAO> load(String code) {
        return super.load(code);
    }

    @Override
    public JPAResult<Boolean> delete(String code) {
        return super.delete(code);
    }

    @Override
    public JPAResult<Boolean> delete(PaysDAO entity) {
        if (entity != null) {
            return super.delete(entity.getCode());
        }
        return new JPAResult<>(Optional.of(false));
    }

    @Override
    public JPAResult<Long> countAll() {
        return super.countAll("PaysDAO.countAll", "countAll() PaysJPA");
    }

}
